apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app.gateway.envoyproxy.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: eg
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system-1
  name: envoy-envoy-gateway-system-1-eg
  namespace: envoy-gateway-system-1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.gateway.envoyproxy.io/name: envoy
      gateway.envoyproxy.io/owning-gateway-name: eg
      gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.gateway.envoyproxy.io/name: envoy
        gateway.envoyproxy.io/owning-gateway-name: eg
        gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system-1
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - --service-cluster envoy-gateway-system-1-eg
        - --service-node $(ENVOY_POD_NAME)
        - |
          --config-yaml admin:
            access_log_path: /dev/null
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 19000
          dynamic_resources:
            cds_config:
              resource_api_version: V3
              api_config_source:
                api_type: DELTA_GRPC
                transport_api_version: V3
                grpc_services:
                - envoy_grpc:
                    cluster_name: xds_cluster
                set_node_on_first_message_only: true
            lds_config:
              resource_api_version: V3
              api_config_source:
                api_type: DELTA_GRPC
                transport_api_version: V3
                grpc_services:
                - envoy_grpc:
                    cluster_name: xds_cluster
                set_node_on_first_message_only: true
          node:
            cluster: envoy-gateway-system
            id: envoy-default
          static_resources:
            clusters:
            - connect_timeout: 1s
              load_assignment:
                cluster_name: xds_cluster
                endpoints:
                - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: envoy-gateway
                          port_value: 18000
              http2_protocol_options: {}
              name: xds_cluster
              type: STRICT_DNS
              transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
                  common_tls_context:
                    tls_params:
                      tls_maximum_protocol_version: TLSv1_3
                    tls_certificate_sds_secret_configs:
                    - name: xds_certificate
                      sds_config:
                        path_config_source:
                          path: "/sds/xds-certificate.json"
                        resource_api_version: V3
                    validation_context_sds_secret_config:
                      name: xds_trusted_ca
                      sds_config:
                        path_config_source:
                          path: "/sds/xds-trusted-ca.json"
                        resource_api_version: V3
          layered_runtime:
            layers:
              - name: runtime-0
                rtds_layer:
                  rtds_config:
                    resource_api_version: V3
                    api_config_source:
                      transport_api_version: V3
                      api_type: DELTA_GRPC
                      grpc_services:
                        envoy_grpc:
                          cluster_name: xds_cluster
                  name: runtime-0
        - --log-level info
        command:
        - envoy
        env:
        - name: ENVOY_GATEWAY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: ENVOY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: envoyproxy/envoy:v1.23-latest
        imagePullPolicy: IfNotPresent
        name: envoy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: certs
          readOnly: true
        - mountPath: /sds
          name: sds
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: envoy-envoy-gateway-system-1-eg
      serviceAccountName: envoy-envoy-gateway-system-1-eg
      terminationGracePeriodSeconds: 300
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: envoy
      - configMap:
          defaultMode: 420
          items:
          - key: xds-trusted-ca.json
            path: xds-trusted-ca.json
          - key: xds-certificate.json
            path: xds-certificate.json
          name: envoy-envoy-gateway-system-1-eg
          optional: false
        name: sds

