apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-4 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-6
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-7
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-8
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-9
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system-10
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: envoy-gateway-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - referencegrants
  - referencepolicies
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: envoy-gateway-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: envoy-gateway-role
subjects:
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-1
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-2
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-3
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-4
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-5
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-6
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-7
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-8
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-9
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-10
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy-role
subjects:
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-1
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-2
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-3
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-4
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-5
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-6
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-7
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-8
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-9
- kind: ServiceAccount
  name: envoy-gateway
  namespace: envoy-gateway-system-10